//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Compra()
        {
            this.P_ClientePessoa = new HashSet<P_ClientePessoa>();
        }
    
        public int ID_COMPRA { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_EMISSA { get; set; }
        public Nullable<System.DateTime> DATA_ENTREGA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_ClientePessoa> P_ClientePessoa { get; set; }
    }
}
