//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Tecnicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Tecnicos()
        {
            this.O_OrdemServico = new HashSet<O_OrdemServico>();
        }
    
        public int ID_TECNICO { get; set; }
        public string NOME { get; set; }
        public string ABREVIACAO { get; set; }
        public string ENDERECO { get; set; }
        public string TELEFONE { get; set; }
        public string TELEFONE2 { get; set; }
        public string CELULAR { get; set; }
        public string CELULAR2 { get; set; }
        public string SITUACAO { get; set; }
        public string BAIRRO { get; set; }
        public string EMAIL { get; set; }
        public string CEP { get; set; }
        public string OBSERVACAO { get; set; }
        public string SEXO { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public Nullable<System.DateTime> DATA_NASCIMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_OrdemServico> O_OrdemServico { get; set; }
    }
}
