//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_OrdemServico
    {
        public int ID_ORDEM_SERVICO { get; set; }
        public int ID_PESSOA_CLIENTE { get; set; }
        public int ID_SERVICO { get; set; }
        public Nullable<int> NUMERO_OS { get; set; }
        public Nullable<int> ID_CONTATOP { get; set; }
        public Nullable<int> ID_TECNICO { get; set; }
        public string ORIGEM_CHAMADO { get; set; }
        public string SERVICOS_EXECUTADOS { get; set; }
        public string VALOR_OBRA { get; set; }
        public string TECNICO_SERVICO { get; set; }
        public Nullable<System.DateTime> DATA_INICIO { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string ESTADO { get; set; }
    
        public virtual G_Tecnicos G_Tecnicos { get; set; }
        public virtual P_ClientePessoa P_ClientePessoa { get; set; }
    }
}
