//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Servico
    {
        public int ID_SERVICO { get; set; }
        public Nullable<int> ID_PRODUTO { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<double> VALOR { get; set; }
    
        public virtual P_Produto P_Produto { get; set; }
    }
}
