//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ClientePessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_ClientePessoa()
        {
            this.O_OrdemServico = new HashSet<O_OrdemServico>();
        }
    
        public int ID_PESSOA { get; set; }
        public Nullable<int> ID_PESSOA_TIPO { get; set; }
        public Nullable<int> ID_CIDADE { get; set; }
        public Nullable<int> ID_COMPRA { get; set; }
        public Nullable<int> ID_CONTATOP { get; set; }
        public Nullable<int> ID_MS { get; set; }
        public Nullable<int> ID_OS { get; set; }
        public string NOME { get; set; }
        public string ENDERECO { get; set; }
        public string TELEFONE { get; set; }
        public string TELEFONE2 { get; set; }
        public string FAX_TELEFONE { get; set; }
        public string TELEX_TELEFONE { get; set; }
        public string SITUACAO { get; set; }
        public string BAIRRO { get; set; }
        public string EMAIL { get; set; }
        public string CEP { get; set; }
        public string OBSERVACAO { get; set; }
        public string TIPO { get; set; }
        public string CP_MUNICIPIO { get; set; }
        public string MUNICIPIO { get; set; }
        public string PAIS { get; set; }
        public string DESC_PAIS { get; set; }
        public string NIVEL { get; set; }
    
        public virtual C_Compra C_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_OrdemServico> O_OrdemServico { get; set; }
        public virtual P_Cidade P_Cidade { get; set; }
        public virtual P_PessoaContatos P_PessoaContatos { get; set; }
        public virtual P_Fisica P_Fisica { get; set; }
        public virtual P_Juridica P_Juridica { get; set; }
    }
}
