//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Juridica
    {
        public int ID_PESSOA_JURIDICA { get; set; }
        public Nullable<int> ID_PESSOA_TIPO { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public string CNPJ { get; set; }
        public string NOME_CONTATO { get; set; }
        public string INSCRICAO_STADUAL { get; set; }
    
        public virtual P_ClientePessoa P_ClientePessoa { get; set; }
    }
}
