//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_Produto()
        {
            this.O_Servico = new HashSet<O_Servico>();
        }
    
        public int ID_PRODUTO { get; set; }
        public Nullable<int> ID_PRODUTO_MARCA { get; set; }
        public Nullable<int> ID_PRODUTO_GRUPO { get; set; }
        public Nullable<int> ID_VENDA { get; set; }
        public Nullable<int> ID_COMPRA { get; set; }
        public Nullable<int> ID_FORNECEDOR { get; set; }
        public string NOME { get; set; }
        public string CODIGO_BARRA { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> ESTOQUE_MINIMO { get; set; }
        public Nullable<int> ESTOQUE_MAXIMO { get; set; }
        public Nullable<double> PRECO_CUSTO { get; set; }
        public Nullable<double> PRECO_VENDA { get; set; }
    
        public virtual F_FornecedorPessoa F_FornecedorPessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<O_Servico> O_Servico { get; set; }
        public virtual P_ProdutoGrupo P_ProdutoGrupo { get; set; }
        public virtual P_ProdutoMarca P_ProdutoMarca { get; set; }
    }
}
