//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Venda
    {
        public int ID_VENDA { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_ENTREGA { get; set; }
    }
}
